# These first lines load the all routes defined as @Route() annotations in any
# controller defined inside the src/AppBundle/Controller/ directory. Controllers
# are loaded recursively, so you can separate them into subdirectories.
# If you don't like to add annotations in your applications, you can also define
# the routes in YAML, XML or PHP files.
# See https://symfony.com/doc/current/book/routing.html
application:
    resource: "@ApplicationBundle/Controller/"
    prefix  : "/"
    type    : "annotation"
